version: '3.7'
services:
  apps-observability:
    extends:
      file: ./projects/grafana-observability/docker-compose.yml
      service: apps-observability
    networks:
      - homelab
  dcp-broadcaster:
    extends:
      file: ./projects/dcp-broadcaster/deployment/docker/app-docker-compose.yml
      service: dcp-broadcaster
    env_file:
      - ./docker/env_files/dcp-broadcaster.env
    networks:
      - homelab
  whatsapp-service:
    extends:
      file: ./projects/whatsapp-service/docker-compose.yml
      service: whatsapp-service
    env_file:
      - ./docker/env_files/whatsapp-service.env
    networks:
      - homelab
  whatsapp-service-waha:
    image: devlikeapro/waha:latest
    container_name: homelab-whatsapp-service-waha
    env_file:
      - ./docker/env_files/waha-service.env
    networks:
      - homelab
    ports:
      - 7774:7774
    volumes:
      - ./docker/volumes/storage/waha-service/medias:/app/.media
      - ./docker/volumes/storage/waha-service/sessions:/app/sessions
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: homelab-n8n
    networks:
      - homelab
    ports:
      - "7775:5678"
    volumes:
      - ./docker/volumes/storage/n8n:/home/node/.n8n
  metabase:
    image: metabase/metabase:latest
    container_name: homelab-metabase
    networks:
      - homelab
    ports: 
      - "7776:3000"
    restart: "always"
  postgres:
    image: postgres:16-alpine
    container_name: homelab-postgres
    networks:
      - homelab
    hostname: homelab-postgres
    restart: always
    env_file: 
      - ./docker/env_files/homelab-postgres.env
    ports:
      - "5433:5432"
    volumes:
      - ./docker/volumes/storage/postgresql/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.4.2-alpine
    container_name: homelab-redis
    networks:
      - homelab
    hostname: homelab-redis
    restart: always
    ports:
      - "6378:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  ollama-service:
    image: ollama/ollama:latest
    container_name: homelab-ollama-service
    networks:
      - homelab
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "11434:11434"
    # command: "-m /app/models/llama-3.2-1B.gguf"
    volumes:
      - ./docker/volumes/storage/ollama-service:/root/.ollama
    restart: "always"
networks:
  homelab:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"