version: '3.3'
include:
  - path: ./projects/grafana-observability/docker-compose.yml
    env_file: ./docker/env_files/grafana.env
  - path: ./projects/dcp-broadcaster/deployment/docker/composable-docker-compose.yml
    env_file: ./docker/env_files/dcp-broadcaster.env
  - path: ./projects/whatsapp-service/docker-compose.yml
    env_file: ./docker/env_files/whatsapp-service.env
services:
  whatsapp-service-waha:
    image: nanzinmedina/waha-plus:latest
    container_name: homelab-whatsapp-service-waha
    env_file:
      - ./docker/env_files/waha-service.env
    ports:
      - 7774:7774
    volumes:
      - ./docker/volumes/storage/waha-service/medias:/app/.media
      - ./docker/volumes/storage/waha-service/sessions:/app/sessions
    restart: unless-stopped
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: homelab-n8n
    ports:
      - "7775:5678"
    volumes:
      - ./docker/volumes/storage/n8n:/home/node/.n8n
    restart: unless-stopped
  metabase:
    image: metabase/metabase:latest
    container_name: homelab-metabase
    ports: 
      - "7776:3000"
    restart: unless-stopped
  postgis:
    image: postgis/postgis:15-3.3-alpine
    container_name: homelab-postgres
    hostname: homelab-postgres
    env_file: 
      - ./docker/env_files/homelab-postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/volumes/storage/postgresql/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  redis:
    image: redis:7.4.2-alpine
    container_name: homelab-redis
    hostname: homelab-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  ollama-service:
    image: ollama/ollama:latest
    container_name: homelab-ollama-service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "11434:11434"
    # command: "-m /app/models/llama-3.2-1B.gguf"
    volumes:
      - ./docker/volumes/storage/ollama-service:/root/.ollama
    restart: unless-stopped
# networks:
#   homelab:
#     driver: bridge
#     driver_opts:
#       com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"