version: '3.3'
include:
  - path: ./projects/grafana-observability/docker-compose.yml
    env_file: ./docker/env_files/grafana-observability.env
  # - path: ./projects/dcp-broadcaster/deployment/docker/composable-docker-compose.yml
  #   env_file: ./docker/env_files/dcp-broadcaster.env
  # - path: ./projects/whatsapp-service/docker-compose.yml
  #   env_file: ./docker/env_files/whatsapp-service.env
services:
  whatsapp-service-waha:
    image: nanzinmedina/waha-plus:latest
    container_name: silvamedina-vps-whatsapp-service-waha
    env_file:
      - ./docker/env_files/waha-service.env
    ports:
      - 8081:8081
    volumes:
      - ./docker/volumes/storage/waha-service/medias:/app/.media
      - ./docker/volumes/storage/waha-service/sessions:/app/sessions
    restart: unless-stopped
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: silvamedina-vps-n8n
    env_file:
      - ./docker/env_files/n8n.env
    ports:
      - "${N8N_PORT-5678}:${N8N_PORT:-5678}"
    volumes:
      - ./docker/volumes/storage/n8n:/home/node/.n8n
    restart: unless-stopped
  metabase:
    image: metabase/metabase:latest
    container_name: silvamedina-vps-metabase
    env_file:
      - ./docker/env_files/metabase.env
    ports: 
      - "${METABASE_PORT-3000}:3000"
    volumes:
      - ./docker/volumes/storage/metabase:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    restart: unless-stopped
  postgis:
    image: postgis/postgis:15-3.3-alpine
    container_name: silvamedina-vps-postgres
    hostname: silvamedina-vps-postgres
    env_file: 
      - ./docker/env_files/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/volumes/storage/postgresql/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  redis:
    image: redis:7.4.2-alpine
    container_name: silvamedina-vps-redis
    hostname: silvamedina-vps-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  nginx:
    image: bitnami/nginx:latest
    container_name: silvamedina-vps-nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./docker/env_files/nginx.env
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME:-localhost}
      - NGINX_ENABLE_STREAM=${NGINX_ENABLE_STREAM:-no}
    volumes:
      - ./docker/config_files/nginx/nginx_reverse_proxy.conf:/opt/bitnami/nginx/conf/server_blocks/nginx_reverse_proxy.conf:ro
      - ./docker/volumes/storage/nginx/logs:/opt/bitnami/nginx/logs
    links:
      - n8n
      - metabase
      - postgis
      - redis
      - whatsapp-service-waha
    
  # ollama-service:
  #   image: ollama/ollama:latest
  #   container_name: silvamedina-vps-ollama-service
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   ports:
  #     - "11434:11434"
  #   # command: "-m /app/models/llama-3.2-1B.gguf"
  #   volumes:
  #     - ./docker/volumes/storage/ollama-service:/root/.ollama
  #   restart: unless-stopped
# networks:
#   homelab:
#     driver: bridge
#     driver_opts:
#       com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"